# This is your secret password for the beta app.
# Choose something more secure than this for a real application!
PASSWORD = beta2025!
PASSWORD_ACT0 = "beta0"
PASSWORD_ACT1 = "beta1"
PASSWORD_ACT2 = "beta2"
PASSWORD_ACT3 = "beta3"
